version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
