version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_slug}}/"
    schedule:
      interval: "monthly"
